vich_uploader:
    db_driver: orm


    mappings:
        gallery:
            uri_prefix: /images/gallery
            upload_destination: '%kernel.project_dir%/public/images/gallery'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
