controllers:
    resource: ../src/Controller/
    type: attribute

app_reservation:
    path: '/reservation'
    controller: App\Controller\ReservationController::index
    methods: [ 'GET', 'POST' ]

app_reservation_show:
    path: '/reservations'
    controller: App\Controller\ReservationController::showAllReservations
    methods: [ 'GET' ]

reservation_delete:
    path: '/reservation/delete'
    controller: App\Controller\ReservationController::deleteMultiple
    methods: [ 'POST' ]

app_register:
    path: '/register'
    controller: App\Controller\RegistrationController::register
    methods: [ 'GET', 'POST' ]

app_reservation_seats:
    path: '/reservation/seats'
    controller: App\Controller\ReservationController::getAvailableSeats
    methods: [ 'POST' ]