controllers:
    resource: ../src/Controller/
    type: attribute

app_reservation_check_availability:
    path: '/reservation/check-availability'
    controller: App\Controller\ReservationController::checkAvailability
    methods: [ 'POST' ]

app_reservation_show:
    path: '/reservations'
    controller: App\Controller\ReservationController::showAllReservations
    methods: [ 'GET' ]

reservation_delete:
    path: '/reservation/{id}/delete'
    controller: App\Controller\ReservationController::delete
    methods: [ 'DELETE', 'POST' ]